# -*- coding: utf-8 -*-
"""mikolaj_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XVFdA1BHfRtoBvY4xnFpgsBkd23dOb5
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Ustawienie tytułu aplikacji w Streamlit
st.title("🎅 Rysunek Świętego Mikołaja w Streamlit 🎁")
st.write("Wygenerowano grafikę za pomocą bibliotek Matplotlib i Patches.")

# --- FUNKCJA RYSUJĄCA ---
def draw_santa():
    # Konfiguracja wykresu (tworzymy figurę i osie)
    fig, ax = plt.subplots(figsize=(8, 10))

    # Ustawienia osi
    ax.set_aspect('equal')
    ax.set_xlim(-15, 15)
    ax.set_ylim(-25, 12)
    ax.axis('off') # Ukrywamy osie

    # --- MIKOŁAJ ---

    # --- CZAPKA ---
    # Główna część czapki (trójkąt)
    ax.add_patch(patches.Polygon([(-3.5, 1.5), (3.5, 1.5), (0, 8)], closed=True,
                                 facecolor='red', edgecolor='black', linewidth=1))
    # Biały pasek futra na czapce
    ax.add_patch(patches.Rectangle((-4.5, 0.5), 9, 1, facecolor='white', edgecolor='black', linewidth=1))
    # Pompon
    ax.add_patch(patches.Circle((0, 8.5), 1, facecolor='white', edgecolor='black', linewidth=1))

    # --- GŁOWA ---
    ax.add_patch(patches.Circle((0, -0.5), 4, facecolor='#FCDCB8', edgecolor='black', linewidth=1, zorder=3))

    # --- OCZY (CZARNE KROPKI) ---
    ax.add_patch(patches.Circle((-1.8, 1.2), 0.4, facecolor='black', edgecolor='black', linewidth=1, zorder=4))
    ax.add_patch(patches.Circle((1.8, 1.2), 0.4, facecolor='black', edgecolor='black', linewidth=1, zorder=4))

    # --- NOS ---
    ax.add_patch(patches.Circle((0, 0), 0.8, facecolor='red', edgecolor='black', linewidth=1, zorder=4))

    # --- USTA (Łuk) ---
    ax.add_patch(patches.Arc((0, -1.5), 4, 2, angle=0, theta1=200, theta2=340,
                             edgecolor='black', lw=2, capstyle='round', zorder=4))

    # --- BRODA (Duży biały kształt) ---
    broda_oval = patches.Ellipse((0, -5), 10, 10, angle=0, facecolor='white', edgecolor='black', linewidth=1, zorder=2)
    ax.add_patch(broda_oval)

    # --- TUŁÓW ---
    ax.add_patch(patches.Rectangle((-4.5, -13), 9, 13, facecolor='red', edgecolor='black', linewidth=1))
    # Białe mankiety rękawów
    ax.add_patch(patches.Rectangle((-6.5, -9), 2, 4, facecolor='white', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((4.5, -9), 2, 4, facecolor='white', edgecolor='black', linewidth=1))

    # --- DŁONIE (Te same, co kolor twarzy) ---
    ax.add_patch(patches.Circle((-6, -7), 1.2, facecolor='#FCDCB8', edgecolor='black', linewidth=1, zorder=1))
    ax.add_patch(patches.Circle((6, -7), 1.2, facecolor='#FCDCB8', edgecolor='black', linewidth=1, zorder=1))

    # --- PAS ---
    ax.add_patch(patches.Rectangle((-5.5, -10.5), 11, 2, facecolor='black', edgecolor='black', linewidth=1))

    # --- KLAMRA PASA ---
    ax.add_patch(patches.Rectangle((-2.5, -11.5), 5, 4, facecolor='gold', edgecolor='black', linewidth=1, zorder=1))
    # Wewnętrzny otwór klamry
    ax.add_patch(patches.Rectangle((-1.5, -10.5), 3, 2, facecolor='black', edgecolor='black', linewidth=1, zorder=1))

    # --- NOGI I BUTY ---
    ax.add_patch(patches.Rectangle((-3.5, -20), 3, 7, facecolor='red', edgecolor='black', linewidth=1)) # Lewa noga
    ax.add_patch(patches.Rectangle((0.5, -20), 3, 7, facecolor='red', edgecolor='black', linewidth=1)) # Prawa noga
    ax.add_patch(patches.Rectangle((-4, -22), 4, 2, facecolor='black', edgecolor='black', linewidth=1)) # Lewy but
    ax.add_patch(patches.Rectangle((0, -22), 4, 2, facecolor='black', edgecolor='black', linewidth=1)) # Prawy but

    # --- PREZENTY (Lewa Strona) ---
    ax.add_patch(patches.Rectangle((-13, -22), 5, 5, facecolor='red', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((-11.5, -22), 2, 5, facecolor='green', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((-13, -19.5), 5, 2, facecolor='green', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((-10, -18), 4, 4, facecolor='green', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((-8.8, -18), 1.5, 4, facecolor='red', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((-10, -16.8), 4, 1.5, facecolor='red', edgecolor='black', linewidth=1))

    # --- PREZENTY (Prawa Strona) ---
    ax.add_patch(patches.Rectangle((8, -22), 5, 5, facecolor='blue', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((9.5, -22), 2, 5, facecolor='gold', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((8, -19.5), 5, 2, facecolor='gold', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((7, -18), 4, 4, facecolor='blue', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((8.2, -18), 1.5, 4, facecolor='yellow', edgecolor='black', linewidth=1))
    ax.add_patch(patches.Rectangle((7, -16.8), 4, 1.5, facecolor='yellow', edgecolor='black', linewidth=1))

    # Tytuł dla Matplotlib
    ax.set_title("Wizualizacja Matplotlib: Święty Mikołaj", fontsize=14)

    # Zwracamy obiekt figury, aby Streamlit mógł go wyświetlić
    return fig

# Wywołanie funkcji i wyświetlenie w Streamlit
st.pyplot(draw_santa())

# Informacja w konsoli (nie jest potrzebna w Streamlit, ale dla kompletności)
# print("\n--- Wygenerowano Mikołaja z Matplotlib. Oczy są widoczne! ---")